services:
  meshtastic-mqtt:
    build: .
    container_name: meshtastic-mqtt
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
