services:
  meshtastic-mqtt:
    build: .
    container_name: meshtastic-mqtt
    ports:
      - "8883:8883"
    volumes:
      - ./data:/app/data
      - /etc/letsencrypt/live/mqtt.deftastic.com:/app/certs:ro
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production