version: "3.8"

services:
  meshtastic-mqtt:
    build:
      context: .
    container_name: meshtastic-mqtt
    ports:
      - "8883:8883"
    volumes:
      - ./certificate.pfx:/app/certificate.pfx
      - ./broker.db:/app/broker.db
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
