version: "3.8"

services:
  meshtastic-mqtt:
    image: defcontastic/deftastic:latest
    container_name: meshtastic-mqtt
    ports:
      - "8883:8883"
    volumes:
      - ./data:/app/data
      - /etc/letsencrypt/live/mqtt.deftastic.com/fullchain.pem:/app/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/mqtt.deftastic.com/privkey.pem:/app/certs/privkey.pem:ro
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8883/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dashboard:
    image: defcontastic/deftastic-dashboard:latest
    container_name: deftastic-dashboard
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/dashboard.deftastic.com/fullchain.pem:/etc/caddy/cert.pem:ro
      - /etc/letsencrypt/live/dashboard.deftastic.com/privkey.pem:/etc/caddy/key.pem:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s