services:
  meshtastic-mqtt:
    build:
      context: .
    container_name: meshtastic-mqtt
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./data:/app/data
      - ./certificate.pfx:/app/certificate.pfx
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
