version: "3.8"

services:
  meshtastic-mqtt:
    image: defcontastic/deftastic:latest
    container_name: meshtastic-mqtt
    ports:
      - "8883:8883"
    volumes:
      - ./data:/app/data
      - /etc/letsencrypt/archive/mqtt.deftastic.com:/app/certs:ro
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production