name: Auto Deploy

on:
  push:
    branches:
      - master  # Trigger deploy on push to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push MQTT Broker
        run: |
          echo "Building MQTT Broker image..."
          docker build -t defcontastic/deftastic:latest .
          echo "Pushing MQTT Broker image..."
          docker push defcontastic/deftastic:latest

      - name: Build and Push Dashboard
        run: |
          echo "Building Dashboard image..."
          cd web
          docker build -t defcontastic/deftastic-dashboard:latest .
          echo "Pushing Dashboard image..."
          docker push defcontastic/deftastic-dashboard:latest

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} 'echo "SSH connection successful"'

      - name: SSH Deploy to Server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            echo "Starting deployment..."
            cd ~/mqtt
            echo "Resetting git state..."
            git reset --hard
            git clean -fd
            echo "Pulling latest changes..."
            git pull origin master
            echo "Removing override file..."
            rm -f docker-compose.override.yml
            echo "Stopping containers..."
            docker compose down
            echo "Removing old images..."
            docker image rm defcontastic/deftastic:latest defcontastic/deftastic-dashboard:latest || true
            echo "Pulling new images..."
            docker pull defcontastic/deftastic:latest
            docker pull defcontastic/deftastic-dashboard:latest
            echo "Starting services..."
            docker compose up -d
            echo "Checking service health..."
            sleep 10
            docker compose ps
            echo "Deployment complete!"